server:
  port: 8282
spring:
  datasource:
    url: jdbc:postgresql://51.250.22.199:5432/postgresdb?currentSchema=tasks_schema
    username: postgresuser
    password: secret123
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasks_schema

springdoc:
  override-with-generic-response: false
  api-docs:
    path: /api-docs

my:
  SECRET: ${SECRET}
  #JWT token validity in seconds
  JWT_TOKEN_VALIDITY: ${JWT_TOKEN_VALIDITY}